function check_distribution(Z, pd, varargin)
% Check if values generated by random sampling match the distribution
%
% Syntax
%   check_distribution(Z, pd)
%
%  Input Arguments
%    Z - Random samples
%      array
%    pd - Probability distribution name
%      character vector or string scalar of probability distribution name

n_bins = numel(Z) / 1000;

% Plot empirical distribution
h = histogram(Z, n_bins, 'Normalization', 'pdf', 'FaceColor', 'b', 'FaceAlpha', 0.2);
hold on

% Plot actual distribution
xmin = h.BinLimits(1); xmax = h.BinLimits(2);
xx = linspace(xmin, xmax, n_bins);
plot(xx, pdf(pd, xx, varargin{:}))
